### ISSUE TITLE
make on centos

### ISSUE THREAD

**Issue by vastyao** [MPI-IS/mesh#11]
when I make this project on centos ,there would be an error "TypeError: 'include_dirs' (if supplied) must be a list of strings"? What can I do for this? I am looking for your relay? Thank you very much.

**Comment by Dawars** [comment]
Probably you are using python 2, try my Python 3 port in the pull request.

**Comment by vastyao** [comment]
OK， I will try this, thank you very much.

**Comment by Dawars** [comment]
Did you have the time to try this?

If the issue is resolved, please close the issue.

**Comment by vastyao** [comment]
I have try， but it did not work.  However, thank you very much.

**Comment by CRISZJ** [comment]
I have the same problem. When I make this project on Ubuntu16.04, it also has the same error.

**Comment by tranquangchung** [comment]
Me too, Anyone help me ?

**Comment by bala1144** [comment]
I have also the same issue in Ubunut16.04, I am trying to install it for Octopus pkl issue. Any one solved it already ?
