### ISSUE TITLE
draw 3d shapes with each the color of vertices belonging to some color map

### ISSUE THREAD

**Issue by sw-gong** [MPI-IS/mesh#13]
Hi,

Thanks for the library.

Could anyone show a simple example of drawing a few meshes in a row with a specific background (e.g., white) and the colors of vertices belonging to some color map that is given by values of vertices?

Like the image shown below:

![image](https://user-images.githubusercontent.com/39670256/62493203-73768480-b7c8-11e9-926e-b40713ea23aa.png)

**Comment by Eby-123** [comment]
@sw-gong Great!
How to do that?Which file did you run?
