### ISSUE TITLE
Given no hashes to check 127 links for project 'pip': discarding no candidates ####### Cleaning some artifacts ####### Touching the result

### ISSUE THREAD

**Issue by fox16789** [MPI-IS/mesh#15]
make:always found link: pip  link of various version.

Successfully built psbody-mesh
Installing collected packages: psbody-mesh

Successfully installed psbody-mesh-0.1
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-hak2zb'
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 11972
Analyzing links from page https://pypi.org/simple/pip/
  Found link https://files.pythonhosted.org/packages/3d/9d/1e313763bdfb6a48977b65829c6ce2a43eaae29ea2f907c8bbef024a7219/pip-0.2.tar.gz#sha256=88bb8d029e1bf4acd0e04d300104b7440086f94cc1ce1c5c3c31e3293aee1f81 (from https://pypi.org/simple/pip/), version: 0.2
  Found link https://files.pythonhosted.org/packages/18/ad/c0fe6cdfe1643a19ef027c7168572dac6283b80a384ddf21b75b921877da/pip-0.2.1.tar.gz#sha256=83522005c1266cc2de97e65072ff7554ac0f30ad369c3b02ff3a764b962048da (from https://pypi.org/simple/pip/), version: 0.2.1
......

Found link https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl#sha256=340a0ba40fdeb16413914c0fcd8e0b4ebb0bf39a900ec80e11c05d836c05103f (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.3
  Found link https://files.pythonhosted.org/packages/00/9e/4c83a0950d8bdec0b4ca72afd2f9cea92d08eb7c1a768363f2ea458d08b4/pip-19.2.3.tar.gz#sha256=e7a31f147974362e6c82d84b91c7f2bdf57e4d3163d3d454e6c3e71944d67135 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.3
Given no hashes to check 127 links for project 'pip': discarding no candidates
####### Touching the result

**Comment by bradison18** [comment]
could u please tell how to rectify this error. I am also having the same error

**Comment by ioreshnikov** [comment]
@fox16789 @bradison18 Hey! Can you please provide us with some additional details so we can figure it out:

1. Which version of `mesh` are you trying to install? Please provide the commit hash if possible.
2. Which version of python you are using?

**Comment by fox16789** [comment]
Sorry， it has been a long time for the issue, and i have forgotten it. Anyway i had solved it later. THX for your reply.

**Comment by ashwath98** [comment]
Hey how do you remmember how you resolved this issue?
I am running 
BOOST_INCLUDE_DIRS=/usr/include/boost/ make all
from the mesh directory and facing the same issue
