### ISSUE TITLE
meshviewer in a remote device where no display is available

### ISSUE THREAD

**Issue by sunit1409** [MPI-IS/mesh#18]
I want to do the meshviewer in a remote google cloud  instance where I want to use the save_snapshot function to dump into images. I tried that but since google cloud instances does not allow the same I get errors.

OpenGL test failed: 
        stdout: 
        stderr: freeglut (foo): failed to open display ''

How can I use the meshviewerremote class for the same. 

@anuragranj  can u help

**Comment by Qingcsai** [comment]
Yeah, I met the same problems when I try to open the meshviewer from the remote server connected by ssh, which got the errors：

> OpenGL test failed:
> stdout:
> stderr: freeglut (foo): failed to open display ''

I think maybe I should save the models locally and visiualize it locally by some applications, but I do not know how to save the mesh models, could u help me? @anuragranj

**Comment by ioreshnikov** [comment]
@sunit1409 @Qingcsai Hey! 

Sorry for the long reply, all the relevant discussion happened in #29 and I forgot to update this issue. We have come up with a workaround to render the meshes from a remote machine. Please see this section of the README

https://github.com/MPI-IS/mesh#viewing-the-meshes
