### ISSUE TITLE
Mesh doesn't work on Python2.7 anymore?

### ISSUE THREAD

**Issue by tobyclh** [MPI-IS/mesh#20]
Hi, I think the recent change in this repo breaks it for python2.7, which is required for the VOCA project from MPI.
I have also opened [an issue at the VOCA repo](https://github.com/TimoBolkart/voca/issues/20)

**Comment by neonb88** [comment]
Has anyone made this repo work with python2.7?

**Comment by TimoBolkart** [comment]
> Hi, I think the recent change in this repo breaks it for python2.7, which is required for the VOCA project from MPI.
> I have also opened [an issue at the VOCA repo](https://github.com/TimoBolkart/voca/issues/20)

VOCA works now also for Python 3. 

If you still need the mesh package for python2.7, just use this [old fork](https://github.com/TimoBolkart/mesh)

**Comment by ioreshnikov** [comment]
@tobyclh you're absolutely correct. Starting from v0.2 mesh no longer works on python2.7. If this is absolutely necessary for you, you can use the fork mentioned by @TimoBolkart or simply checkout commit 1761d54 in this repository, which is a merge of @TimoBolkart pull request.

**Comment by hshreeshail** [comment]
> > Hi, I think the recent change in this repo breaks it for python2.7, which is required for the VOCA project from MPI.
> > I have also opened [an issue at the VOCA repo](https://github.com/TimoBolkart/voca/issues/20)
> 
> VOCA works now also for Python 3.
> 
> If you still need the mesh package for python2.7, just use this [old fork](https://github.com/TimoBolkart/mesh)

The Makefile of the old fork works when installing to a python virtualenv. How do I instead install MPI Mesh (Python 2.7 version) to a conda environment? I need it since I am working with [Multi Garment Network](https://github.com/bharat-b7/MultiGarmentNetwork)
