### ISSUE TITLE
make all error

### ISSUE THREAD

**Issue by yangbiaobiao500** [MPI-IS/mesh#21]
![Screenshot from 2019-11-26 16-30-10](https://user-images.githubusercontent.com/48718462/69612103-0e41ea00-106a-11ea-9aed-da1771138369.png)

**Comment by bradison18** [comment]
Even i am facing the same error could u please tell how to rectify it.

**Comment by ioreshnikov** [comment]
@yangbiaobiao500 @bradison18 Hey! Could you please provide us with more context? What are you trying to do and in what environment when you get the error message?

**Comment by ioreshnikov** [comment]
Closing until provided with the information on how to reproduce.
