### ISSUE TITLE
Function save_snapshot() of meshviewer not working

### ISSUE THREAD

**Issue by Arthur151** [MPI-IS/mesh#25]
Nice work! It does support a lot of brilliant works.
But when I try to save the result of meshviewer using  save_snapshot, it fails. Actually, nothing happens. No files are saved.
To check the bug, I run the test_snapshot() of tests/test_meshviewer. It fails also. But the test_launch_smoke_test() success.
Looking forward to your reply.
Besides, is there any ports to convert the image in meshviewer to numpy array for other using?
Thanks for your efforts!

**Comment by Qingcsai** [comment]
I came with the same problem.
After I run 'mvs[0][0].save_snapshot(**)' nothing happens, no files are saved.
Looking forward to your answer@MPI-IS @jcpassy

**Comment by pujades** [comment]
+1 

save_snapshot freezes the MeshViewer

psbody-mesh        0.3  
osx Mojave

**Comment by jcpassy** [comment]
Hi @Arthur151 @Qingcsai @pujades,
thanks a lot for the bug report! :)
I will look into it and let you know.

**Comment by jcpassy** [comment]
Hi @Arthur151 @Qingcsai and @pujades,
The issue was that the mesh had not been fully rendered when the snapshot was taken. The bug has been fixed in the new release **v0.4**. If you still encounter issues, don't hesitate to let us know!
Cheers!
