### ISSUE TITLE
Make all c++ Error in MacOS

### ISSUE THREAD

**Issue by plmsmile** [MPI-IS/mesh#33]
python=3.6.8
installed boost
I have tried `BOOST_ROOT=/usr/local/Cellar/boost/1.71.0 make all` and `make all` commands. Both error occurs.

`   /Users/plm/app/anaconda3/envs/voca/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    In file included from mesh/src/aabb_normals.cpp:10:
    mesh/src/AABB_n_tree.h:6:10: fatal error: 'vector' file not found
    #include <vector>
             ^~~~~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /private/var/folders/xw/h6fs7299027bj682phxtlgph0000gp/T/pip-req-build-vyk3s33j
Command "/Users/plm/app/anaconda3/envs/voca/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xw/h6fs7299027bj682phxtlgph0000gp/T/pip-req-build-vyk3s33j/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xw/h6fs7299027bj682phxtlgph0000gp/T/pip-record-x5knfek7/install-record.txt --single-version-externally-managed --compile --boost-location=/usr/local/Cellar/boost/1.71.0" failed with error code 1 in /private/var/folders/xw/h6fs7299027bj682phxtlgph0000gp/T/pip-req-build-vyk3s33j/
Exception information:
Traceback (most recent call last):
  File "/Users/plm/app/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/Users/plm/app/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/Users/plm/app/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/Users/plm/app/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/Users/plm/app/anaconda3/envs/voca/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/Users/plm/app/anaconda3/envs/voca/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xw/h6fs7299027bj682phxtlgph0000gp/T/pip-req-build-vyk3s33j/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xw/h6fs7299027bj682phxtlgph0000gp/T/pip-record-x5knfek7/install-record.txt --single-version-externally-managed --compile --boost-location=/usr/local/Cellar/boost/1.71.0" failed with error code 1 in /private/var/folders/xw/h6fs7299027bj682phxtlgph0000gp/T/pip-req-build-vyk3s33j/
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
make: *** [all] Error 1
`

**Comment by plmsmile** [comment]
I tried `CFLAGS="-mmacosx-version-min=10.7 -stdlib=libc++" make all` and it solved the problem. Thanks for this issue https://github.com/MPI-IS/mesh/issues/12

**Comment by mahdi943** [comment]
> CFLAGS="-mmacosx-version-min=10.7 -stdlib=libc++" make all

Hi. do you know how can I solve same probblem im Linux?
