### ISSUE TITLE
make: *** No rule to make target 'all'.  Stop.

### ISSUE THREAD

**Issue by Anth0nyWu** [MPI-IS/mesh#39]
Do I need to create another virtual environment if i am already in one, like I am in (voca) right now as shown.
If not, I got the error 
` make: *** No rule to make target 'all'.  Stop.`
when i run 
`make all`.
Do i need to clone repository first or I missed something? 
![image](https://user-images.githubusercontent.com/16257057/81710646-7dd75480-94a5-11ea-850d-4d8e3dc85511.png)

**Comment by jcpassy** [comment]
Hi @Anth0nyWu, what is in your `voca` directory?
Yes, you should clone the repository and go to the mesh directory:

1. `git clone https://github.com/MPI-IS/mesh.git`
2. `cd mesh`
3. `make all`


The `make all` command should be executed where the `Makefile` is.

**Comment by jcpassy** [comment]
No answer so I assume everything works! :)
