### ISSUE TITLE
 installation of Windows 10?

### ISSUE THREAD

**Issue by laurapalmer99** [MPI-IS/mesh#4]
Can I Install MPI-IS/mesh on windows?

**Comment by raffienficiaud** [comment]
The code by itself is not specific to mac or linux (even GDAL), but we never took the time to adjust for Windows.

**Comment by laurapalmer99** [comment]
It's a pity, but thanks for your reply. I was trying to install it on windows for hours and I couldn't find out how. so, good to know the answer. :)

**Comment by raffienficiaud** [comment]
If you are able to install boost on Windows, I believe you did 75% of the work. The rest is passing the `--boost-location=$BOOST_ROOT` to the `setup.py` script (and maybe installing the dependencies prior to that, see https://github.com/MPI-IS/mesh/blob/master/Makefile#L62)

**Comment by laurapalmer99** [comment]
I'll give it a try and consider installing Linux if it doen's work. thanks!

**Comment by coloss** [comment]
I've just created PR #34 which should fix the compilation on Windows with MSVC.

**Comment by coloss** [comment]
Could anybody take a look at the PR #34 which fixes the compilation on Win? @jcpassy , @raffienficiaud .

**Comment by jcpassy** [comment]
Hi @coloss , thanks a lot for your PR. We are not forgetting you. :) 
As soon as we have some time to allocate to this project, we will look into it.
Cheers!

**Comment by Qingqingniu** [comment]
Hi, have you install MPI-IS/mesh on windows successfully? I am facing the same problem!

**Comment by Qingqingniu** [comment]
Hi, @laurapalmer99 ，do you install MPI-IS/mesh on windows successfully,could you give me some advice on installing it on windows?

**Comment by zhangyux15** [comment]
I run part of this library in win10 with amd cpu. 
1. First you need to build boost(run bootstrap.bat and b2.exe install prefix =xxxxx) and copy the include dir. 
2. Run "pip install --no-deps --install-option="--boost-location=xxxx\build\include\boost-1_74"" --verbose --no-cache-dir ." 
3. Run "python setup.py sdist" 
4. Run "python setup.py --verbose build_ext --boost-location=xxxx\build\include\boost-1_74  bdist_wheel"
5. step 4 will raise error "can not find CGAL/AABB_tree.h" you need to copy "\build\temp.win-amd64-3.7\CGAL-4.7" to ".\build\temp.win-amd64-3.7\Release\CGAL-4.7"  to fix the path problem
6. Run Step4 again
7. I found that building extension "visibility" will cause linking error, so I commented out the line 203 of setup.py
8. Then you can install the package

**Comment by olga-2020-Feb** [comment]
Hi @zhangyux15 , 
In step 2 I get:
ERROR: You must give at least one requirement to install (see "pip help install")
Could you please check?

Thank you.

**Comment by karan00713** [comment]
Hi @zhangyux15 , what should i have to give in this location ( **--boost-location=xxxx\build\include\boost-1_74** ) ??

**Comment by sssccyyy** [comment]
@olga-2020-Feb have you solve it?

**Comment by Kyle-z1996** [comment]
> Hi @zhangyux15 , In step 2 I get: ERROR: You must give at least one requirement to install (see "pip help install") Could you please check?
> 
> Thank you.

Hi, I got the same problem, have you known how to fix it? Need your help bro!

**Comment by Kyle-z1996** [comment]
> @olga-2020-Feb have you solve it?

Try this command to install: 
    psbody root > python setup.py install --boost-location <boost_root>

It works in my win11 system.

**Comment by qaz8788817** [comment]
> Hi @zhangyux15 , what should i have to give in this location ( **--boost-location=xxxx\build\include\boost-1_74** ) ??

Hi @karan00713 , did you know the answer? Could you tell me? Thanks.

**Comment by qaz8788817** [comment]
> I run part of this library in win10 with amd cpu.
> 
> 1. First you need to build boost(run bootstrap.bat and b2.exe install prefix =xxxxx) and copy the include dir.
> 2. Run "pip install --no-deps --install-option="--boost-location=xxxx\build\include\boost-1_74"" --verbose --no-cache-dir ."
> 3. Run "python setup.py sdist"
> 4. Run "python setup.py --verbose build_ext --boost-location=xxxx\build\include\boost-1_74  bdist_wheel"
> 5. step 4 will raise error "can not find CGAL/AABB_tree.h" you need to copy "\build\temp.win-amd64-3.7\CGAL-4.7" to ".\build\temp.win-amd64-3.7\Release\CGAL-4.7"  to fix the path problem
> 6. Run Step4 again
> 7. I found that building extension "visibility" will cause linking error, so I commented out the line 203 of setup.py
> 8. Then you can install the package

Hi @zhangyux15 , when I run the step 4, I got some errors. Could you help me?
![image](https://github.com/MPI-IS/mesh/assets/73918947/c6d8b9e1-598c-4be8-8438-fdc1388b7aac)
And here is my command: ` pip install --no-deps --config-settings="--boost-location=C:\local\boost\include\boost-1_73" --verbose --no-cache-dir . `
