### ISSUE TITLE
About when I use the old folder for python2.7,I found it can't be used

### ISSUE THREAD

**Issue by lll-gen** [MPI-IS/mesh#47]
Requirement already up-to-date: setuptools in ./temporary_test/venv/lib/python2.7/site-packages (45.0.0)
ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'
Makefile:48: recipe for target 'temporary_test/package_creation' failed
make: *** [temporary_test/package_creation] Error 1

the setuptools need python3.5

**Comment by lll-gen** [comment]
i have stuck here ,if you would help me, I'll appreciate

**Comment by ioreshnikov** [comment]
@Lixz123456 Hey! 

Sorry for a long reply. The answer is, unfortunately, that we simply do not support python 2.7 anymore. Python 2 has been considered deprecated for several years and has reached end of life on January 1 2020. I suggest you migrate your code to python3.

Best,
Ivan
