### ISSUE TITLE
how to close the mesh viewer window

### ISSUE THREAD

**Issue by yifanh1** [MPI-IS/mesh#48]
I tried to take snapshots of a number of obj files, so I use a loop in my script. 
I add mv.close (where mv is MeshViewer) at the end but there are more and more viewer windows when the program running. 
```
for fname in .....
target_mesh = Mesh(filename=fname)
mv = target_mesh.show()
mv.save_snapshot(os.path.join(imgfolder, snapshot_name))
mv.close
```
How to actually close the windows while it loops and avoid too many active windows at the same time?

**Comment by Adorablepet** [comment]
@yifanh1 how to solve this problem? Could you tell me? thanks.

**Comment by yifanh1** [comment]
> @yifanh1 how to solve this problem? Could you tell me? thanks.

should be 
```
mv.close()
```
