### ISSUE TITLE
Installation Issue :  Given no hashes to check 151 links for project 'pip': discarding no candidates

### ISSUE THREAD

**Issue by ashwath98** [MPI-IS/mesh#54]
Hey,
I was trying to setup mesh library on a remote system when I faced this issue :
I setup boost as specified ( command whereis boost returns boost: /usr/include/boost )
when I run 
`BOOST_INCLUDE_DIRS=/usr/include/boost/ make all
`
from the mesh directory I get the following error : **Given no hashes to check 151 links for project 'pip': discarding no candidates**

This issue was previously also mentioned in https://github.com/MPI-IS/mesh/issues/15 but no resolution was reported back

System Info 
Python Version : 3.8
OS : Ubuntu 16.04
Clang Version : 3.8
Cmake version : 3.15

**Comment by materdd** [comment]
Same for me. But it works fine because this is kind of pip warning.

![image](https://user-images.githubusercontent.com/27740131/103437008-7566a080-4c65-11eb-8bf7-6887b9ff864e.png)

**Comment by AmitSharma1127** [comment]
Any update on this? I am getting the same error. @materdd  how did you installed it? Can you specify your installation steps?

**Comment by ashwath98** [comment]
It should be installed already, this is just a warning
