### ISSUE TITLE
boost/config.hpp：没有那个文件或目录

### ISSUE THREAD

**Issue by ghost** [MPI-IS/mesh#56]
#warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    In file included from /tmp/pip-req-build-xfu28exo/build/temp.linux-x86_64-3.8/CGAL-4.7/include/CGAL/Profile_counter.h:53:0,
                     from /tmp/pip-req-build-xfu28exo/build/temp.linux-x86_64-3.8/CGAL-4.7/include/CGAL/internal/AABB_tree/AABB_node.h:24,
                     from /tmp/pip-req-build-xfu28exo/build/temp.linux-x86_64-3.8/CGAL-4.7/include/CGAL/internal/AABB_tree/AABB_traversal_traits.h:24,
                     from /tmp/pip-req-build-xfu28exo/build/temp.linux-x86_64-3.8/CGAL-4.7/include/CGAL/AABB_tree.h:26,
                     from mesh/src/AABB_n_tree.h:9,
                     from mesh/src/aabb_normals.cpp:10:
    /tmp/pip-req-build-xfu28exo/build/temp.linux-x86_64-3.8/CGAL-4.7/include/CGAL/config.h:85:10: 致命错误：boost/config.hpp：没有那个文件或目录
     #include <boost/config.hpp>
              ^~~~~~~~~~~~~~~~~~
    编译中断。
    error: command 'gcc' failed with exit status 1
  Running setup.py install for psbody-mesh ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-xfu28exo
Removed build tracker '/tmp/pip-req-tracker-yppvsvz3'

什么问题？

**Comment by jcpassy** [comment]
Hi @chenbolinstudent,
the installer cannot find the Boost libraries. It means that you have either:
* not installed them
* not provided the correct BOOST_INCLUDE_DIRS environment variable.

Please refer to the README for the installation steps. 
Thanks!
