### ISSUE TITLE
C++ errors when installing on MacOs

### ISSUE THREAD

**Issue by cvignac** [MPI-IS/mesh#6]
Hello, 
I'd like to install the library to play with the COMA project. However, I ran into some errors, and I don't manage to debug them all:
- I first tried to install the library using python3.6, but It did not work
- Then, I created a virual environment with python2.7. However, it seems that the "make" command still calls python3.6. I find it surprising, because when I type "python" I enter a python2 console
- I ran into a first python error, saying that ext.include_dirs (in setup.py) should be a list of string, while it was considered as a filter object. I solving by replacing 
`ext.include_dirs = filter(None, ext.include_dirs)`
by:
```
filtered = []  
for x in filter(None, ext.include_dirs):  
    filtered.append(x)  
ext.include_dirs = filtered
```

- Now I am running into another error: 
```
mesh/src/aabb_normals.cpp:43:12: error: use of undeclared identifier
      'Py_InitModule'
    (void) Py_InitModule("aabb_normals", SpatialsearchMethods);
           ^
mesh/src/aabb_normals.cpp:93:26: error: use of undeclared identifier
      'PyCObject_FromVoidPtr'
      PyObject* result = PyCObject_FromVoidPtr((void*)search, aabb_tree_...
                         ^
mesh/src/aabb_normals.cpp:110:40: error: use of undeclared identifier
      'PyCObject_AsVoidPtr'
    TreeAndTri *search = (TreeAndTri *)PyCObject_AsVoidPtr(py_tree);
                                       ^
mesh/src/aabb_normals.cpp:177:40: error: use of undeclared identifier
      'PyCObject_AsVoidPtr'
    TreeAndTri *search = (TreeAndTri *)PyCObject_AsVoidPtr(py_tree);
                                       ^
1 warning and 4 errors generated.
error: command 'gcc' failed with exit status 1
make: *** [temporary_test/package_creation] Error 1
```
This time it's C++ and I don't know how to solve it. Could you help me?

**Comment by anuragranj** [comment]
If you are in a virtual environment, `make` should call `python2`, and not `python3`. Could you `alias python="python2.7" and see if it resolves.

**Comment by cvignac** [comment]
Thank you for your answer. I tried, but it does not make any difference.
As I said before, when I type python from within the virtual environment, it already opens a python2 console.

I don’t understand how it is possible that the script uses python3. Do you have an idea?

**Comment by raffienficiaud** [comment]
It would be good if you can paste all the steps you are doing, and print also your environment (type `env`). Maybe you have something in your `.bashrc` that is preferring python3. The c++ errors you are having seem to be pretty much related to that.

**Comment by cvignac** [comment]
Thank you for this advice, I actually had a line in my bash_profile that would choose python3 for python path. 

Unfortunately, I now have another problem:

/Users/clementvignac/venv/directed_filters/mesh/build/temp.macosx-10.14-x86_64-2.7/CGAL-4.7/include/CGAL/config.h:85:10: fatal error: 
      'boost/config.hpp' file not found
#include <boost/config.hpp>


I tried reinstalling boost from another source (macports instead of brew), but then I got the same error message…


Thanks!

**Comment by skunkwerk** [comment]
Same problem here - can't get it to use python2.7 even inside a python2.7 venv on Mac.  My bash_profile is clean, and I've aliased python to 'python2.7'

Yet it continues to use Python3.7

**Comment by luckybird1994** [comment]
> Thank you for this advice, I actually had a line in my bash_profile that would choose python3 for python path. Unfortunately, I now have another problem: /Users/clementvignac/venv/directed_filters/mesh/build/temp.macosx-10.14-x86_64-2.7/CGAL-4.7/include/CGAL/config.h:85:10: fatal error: 'boost/config.hpp' file not found #include <boost/config.hpp> I tried reinstalling boost from another source (macports instead of brew), but then I got the same error message… Thanks!
> […](#)
> On 7 Mar 2019, at 22:34, Raffi Enficiaud ***@***.***> wrote: It would be good if you can paste all the steps you are doing, and print also your environment (type env). Maybe you have something in your .bashrc that is preferring python3. The c++ errors you are having seem to be pretty much related to that. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I meet the same problem, would you solve it?

**Comment by wangdayan** [comment]
I edit the Makefile with "virtualenv venv --python=python2.7", it worked!
I hope it works for you!

**Comment by guodewen** [comment]
> I edit the Makefile with "virtualenv venv --python=python2.7", it worked!
> I hope it works for you!

Hey, dude. Where did you add the script in the makefile?

**Comment by wangdayan** [comment]
Sorry, I made a mistake, it should be the input command line to create a virtual environment for python2.7.

**Comment by guodewen** [comment]
> Sorry, I made a mistake, it should be the input command line to create a virtual environment for python2.7.

I tried, but it failed with the same errors. It used python3.7 by default.

**Comment by kevinlin311tw** [comment]
I made it works. I did the following modifications.

### First step
In `Makefile`, modify line 55
```
    @virtualenv --system-site-packages $(venv_dir)
```
to 
```
    @virtualenv --python=python2.7 --system-site-package $(venv_dir)
```

### Second step
In `setup.py`, modify line 117
```
    ext.include_dirs = filter(None, ext.include_dirs)
```
to 
```
    filtered = []  
    for x in filter(None, ext.include_dirs):  
        filtered.append(x)  
    ext.include_dirs = filtered
```

**Comment by jcpassy** [comment]
Hi @cvignac @kevinlin311tw @guodewen ,
this is an old ticket so I will close it. 
FYI, the package now supports only Python3 and the installation process does not create a new virtual environment - which is much safer. The user must now create one and activate it before executing the Makefile. This is explained in the README.

Cheers!
