### ISSUE TITLE
Obj files for tests not available

### ISSUE THREAD

**Issue by Dawars** [MPI-IS/mesh#7]
I have been hard at work to port this package to Python 3.

At the end of my endeavor, however, I came to a sudden halt, when I realized that some of the tests depend on **.obj** files in the `data/unittest` directory.
These files are nowhere in sight.

Please mend this at the earliest opportunity.

**Comment by anuragranj** [comment]
Thanks @Dawars . Some of  these files are proprietary and we are not allowed to release them. Alternately, you could use any other object files/ meshes to run the tests.

**Comment by Dawars** [comment]
Thanks!

The most important ones with expected values are:
test_doublebox.obj
hand_fixedbase.obj
cylinder.obj
cylinder_trans.obj
self_intersecting_cyl.obj

test_box.obj
test_box.ply
test_box_le.ply
test_ascii_bad_endings.ply
test_box.pp
sphere.ply

csr0001a.ply
csr0001a.lmrk
textured_mean_scape_female.obj
template_caesar_picked_points.pp


Others:
female_template.ply

**Comment by ioreshnikov** [comment]
Starting from v0.2 208e578 all the unit tests requiring proprietary object-files have been removed from the test suit. Sorry for such a boring solution to the issue :)
